spring:
  application:
    name: security
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:teste
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

token:
  secret: 347c2f96-90b2-44d7-acdc-8c42d69b12f4
