spring:
  application:
    name: security
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/data/security_db
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    root: INFO
    com.security.security.service.PaymentService: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    enable:
      jvm: true
    distribution:
      slo.http.server.requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
    tags:
      application: security-api

token:
  secret: 347c2f96-90b2-44d7-acdc-8c42d69b12f4
